### ISSUE TITLE
Do not bail-out when a static problem is found

### ISSUE THREAD

**Issue by Llorx** [Jam3/babel-plugin-static-fs#15]
A file can have a mix of dynamic and static `fs.readFileSync`, and when a dynamic read is found, throws and error and stops the build.

Simply, if a dynamic read is found, it should continue with the next one, as is not a terminal error actually.

I've modified `static-eval.js` it to achieve this with:
![image](https://user-images.githubusercontent.com/702490/55390597-cb119480-5537-11e9-88a5-96c670f7eb89.png)

Is a ugly workaround, but I had to test if this works. It worked.

Maybe there's a better way to achieve this.

**Comment by mattdesl** [comment]
In my latest commit I tried to get this working, but unfortunately the current approach requires us to evaluate things like `__dirname` into actual string literals before we can determine whether the resulting call is dynamic or not. By the time the dynamic nature is caught, we've already transformed the AST, so if we continue onward you'll end up with bugs in your final source code since some things like `__dirname` will have been transformed when they shouldn't for dynamic calls.

The fix for this is to first clone the path, then evaluate, and only if it succeeds, *then* we replace the path with the cloned & modified/evaluated path. However, I can't for the life of me figure out how to clone a node in babel (`t.cloneNode` doesn't give us back a `NodePath`, just a bare object), and the docs are so sparse that I can't really do anything until somebody with more knowledge of babel's internals chimes in here.

Maybe @azu if you are familiar with the babel APIs?
